# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:31:52+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class RedirectToPostRequest(BaseModel):
    status_code: Optional[int] = None
    url: str


class RedirectToPutRequest(BaseModel):
    status_code: Optional[int] = None
    url: str
